// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class   DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRncx4IQ6UUL5Ic8Oi6L8Y0aWUR5_nn8',
    appId: '1:322980762911:web:6653493255e68163748c2a',
    messagingSenderId: '322980762911',
    projectId: 'ibcjj-fa960',
    authDomain: 'ibcjj-fa960.firebaseapp.com',
    storageBucket: 'ibcjj-fa960.appspot.com',
    measurementId: 'G-WKYZYFXHDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcHEF4Er2UtVK2bO-XdPxsd9TsGMfJsY',
    appId: '1:322980762911:android:5807afdbaaccd728748c2a',
    messagingSenderId: '322980762911',
    projectId: 'ibcjj-fa960',
    storageBucket: 'ibcjj-fa960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXdpYoeCqFUL6yhCCTkpRvs_KaBtUL0w',
    appId: '1:322980762911:ios:911a9bf085838544748c2a',
    messagingSenderId: '322980762911',
    projectId: 'ibcjj-fa960',
    storageBucket: 'ibcjj-fa960.appspot.com',
    iosBundleId: 'com.marysoarez.ibcjjFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXdpYoeCqFUL6yhCCTkpRvs_KaBtUL0w',
    appId: '1:322980762911:ios:911a9bf085838544748c2a',
    messagingSenderId: '322980762911',
    projectId: 'ibcjj-fa960',
    storageBucket: 'ibcjj-fa960.appspot.com',
    iosBundleId: 'com.marysoarez.ibcjjFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRncx4IQ6UUL5Ic8Oi6L8Y0aWUR5_nn8',
    appId: '1:322980762911:web:d450658bbc413734748c2a',
    messagingSenderId: '322980762911',
    projectId: 'ibcjj-fa960',
    authDomain: 'ibcjj-fa960.firebaseapp.com',
    storageBucket: 'ibcjj-fa960.appspot.com',
    measurementId: 'G-XZCX9YBN8K',
  );
}
